from __future__ import annotations

from typing import List, Literal, Optional

from pydantic import BaseModel, Field


class DoorCell(BaseModel):
    col: int
    row: int


class RoomMeta(BaseModel):
    index: int = Field(..., ge=1)
    name: str


class MetricsRequest(BaseModel):
    cols: int = Field(..., ge=1, le=400)
    rows: int = Field(..., ge=1, le=400)
    cells_b64: str
    room_map_b64: str
    doors: List[DoorCell] = Field(default_factory=list)
    rooms: List[RoomMeta] = Field(default_factory=list)
    min_path_width_cells: int = Field(default=1, ge=1, le=8)


class GlobalMetrics(BaseModel):
    total_cells: int
    wall_cells: int
    usable_cells: int
    furniture_cells: int
    furniture_pct: float
    circulation_pct: float
    dead_pct: float
    efficiency_score: float


class RoomMetrics(BaseModel):
    room_index: int
    name: str
    usable_cells: int
    furniture_pct: float
    circulation_pct: float
    dead_pct: float


class MetricsResponse(BaseModel):
    global_metrics: GlobalMetrics
    room_metrics: List[RoomMetrics]
    reachable_mask_b64: str
    dead_mask_b64: str


class ProjectMeta(BaseModel):
    name: str = "Untitled"
    created_at: Optional[str] = None


class UserSummary(BaseModel):
    id: str
    email: str
    name: str
    role: Literal["vendor", "customer", "supplier"]
    phone: str
    created_at: str


class AuthCredentials(BaseModel):
    identifier: str
    password: str = Field(..., min_length=8)


class SignUpRequest(BaseModel):
    name: str = Field(..., min_length=2, max_length=80)
    email: str
    phone: str = Field(..., min_length=7, max_length=20)
    password: str = Field(..., min_length=8)
    role: Literal["vendor", "customer", "supplier"]


class SignInRequest(AuthCredentials):
    pass


class AuthResponse(BaseModel):
    token: str
    user: UserSummary


class ProjectSummary(BaseModel):
    project_id: str
    name: str
    updated_at: str
    created_at: Optional[str] = None
    image_filename: Optional[str] = None
    room_count: int = 0
    furniture_count: int = 0
    customer_name: Optional[str] = None
    customer_location: Optional[str] = None
    project_type: Optional[str] = None
    budget_range: Optional[str] = None
    access_status: Optional[str] = None
    customer_user_id: Optional[str] = None
    vendor_user_id: Optional[str] = None


class DashboardSummaryResponse(BaseModel):
    total_projects: int
    total_rooms: int
    total_furniture: int
    recent_projects: List[ProjectSummary] = Field(default_factory=list)


class ProjectOverviewResponse(BaseModel):
    summary: ProjectSummary
    payload: dict


class ChatAttachment(BaseModel):
    name: str
    content_type: str
    size_bytes: int
    url: str


class LinkPreview(BaseModel):
    url: str
    title: str
    description: Optional[str] = None
    image_url: Optional[str] = None
    site_name: Optional[str] = None


class ChatMessage(BaseModel):
    id: str
    project_id: str
    sender_user_id: str
    sender_name: str
    sender_role: str
    body: str
    created_at: str
    attachment: Optional[ChatAttachment] = None


class ChatMessageListResponse(BaseModel):
    messages: List[ChatMessage] = Field(default_factory=list)


class LinkPreviewResponse(BaseModel):
    preview: LinkPreview


class ProjectSaveRequest(BaseModel):
    project_id: str
    payload: dict


class ProjectSaveResponse(BaseModel):
    ok: bool
    project_id: str


class LocationSuggestion(BaseModel):
    label: str
    lat: float
    lng: float


class LocationSearchResponse(BaseModel):
    suggestions: List[LocationSuggestion] = Field(default_factory=list)


class CleanFloorplanImageRequest(BaseModel):
    """Base64 image (as uploaded in browser) plus declared dimensions for validation."""

    image_b64: str
    mime_type: str = Field(default="image/png", description="e.g. image/png, image/jpeg, image/webp")
    width: int = Field(..., ge=1, le=16000)
    height: int = Field(..., ge=1, le=16000)


class CleanFloorplanImageResponse(BaseModel):
    """PNG raster generated by the image model (walls + doors only, approximate geometry)."""

    image_b64: str
    mime_type: str = Field(default="image/png")
    width: int = Field(..., ge=1)
    height: int = Field(..., ge=1)
    source_width: int
    source_height: int
    model: str
